server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hsfund?serverTimezone=GMT%2b8&allowMultiQueries=true
    username: root
    password:

mybatis:
  type-aliases-package: com.example.businessearch.pojo
  mapper-locations: classpath:mapper/*.xml
